language: java

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

script: ./gradlew clean build

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon

